# Generated by Django 4.2.6 on 2023-10-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
