# Generated by Django 4.2.6 on 2023-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_last_action_user_last_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_last_time',
            field=models.DateTimeField(),
        ),
    ]
