# Generated by Django 4.2.6 on 2023-10-23 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_last_request_alter_user_login_last_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_last_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
