# Generated by Django 4.2.6 on 2023-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_last_login_alter_user_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=90, unique=True),
        ),
    ]
